src/objects/LTA_Bill__c.object
<CustomObject>
    <description>This object houses all Legislative Bill data from Telicon.</description>
    <fields>
        <fullName>Bill_Author__c</fullName>
        <label>Bill Author</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Caption__c</fullName>
        <description>Brief summary of the proposed bill.</description>
        <inlineHelpText>Read-only official caption, automatically updated providing a brief summary of the proposed bill.</inlineHelpText>
        <label>Bill Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Session__c</fullName>
        <label>Bill Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Type__c</fullName>
        <description>Indicated Session Number for this Bill Version.</description>
        <inlineHelpText>Indicated Session Number for this Bill Version.</inlineHelpText>
        <label>Bill Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Indicates when the Final Analysis is due for this Bill Version.</description>
        <inlineHelpText>Indicates when the Final Analysis is due for this Bill Version.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <description>Indicates the proposed bill&apos;s impact categorization.</description>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Significant</fullName>
                </value>
                <value>
                    <fullName>2 - Moderate</fullName>
                </value>
                <value>
                    <fullName>3 - Low</fullName>
                </value>
                <value>
                    <fullName>4 - No Direct Impact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Action__c</fullName>
        <description>Indicates the last action on the Bill within Telicon.</description>
        <inlineHelpText>Indicates the last action on the Bill within Telicon.</inlineHelpText>
        <label>Last Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Legislative_Liaison_SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the Tier A User assignment for this bill.</description>
        <inlineHelpText>The assigned Legislative Liaison responsible for the final analysis of this Bill Version.</inlineHelpText>
        <label>SLA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the appropriate SLA user.</errorMessage>
            <filterItems>
                <field>User.Division__c</field>
                <operation>equals</operation>
                <value>SLA</value>
            </filterItems>
            <filterItems>
                <field>$Source.Subject__c</field>
                <operation>notEqual</operation>
                <value>null</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Telicon (TLO) Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Indicates the proposed bill&apos;s subject categorization.</description>
        <label>TxDOT Subject Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appropriations</fullName>
                </value>
                <value>
                    <fullName>Bike/Ped</fullName>
                </value>
                <value>
                    <fullName>Construction/Letting</fullName>
                </value>
                <value>
                    <fullName>Contracting (Goods &amp; Non.Prof. Services)</fullName>
                </value>
                <value>
                    <fullName>DB/CDA</fullName>
                </value>
                <value>
                    <fullName>Eminent Domain</fullName>
                </value>
                <value>
                    <fullName>Energy Sector</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (Funding - CDL)</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (Funding - Traffic Safety)</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (OS/OW)</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (Other)</fullName>
                </value>
                <value>
                    <fullName>High-Speed Rail</fullName>
                </value>
                <value>
                    <fullName>Highway Memorial Designation</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Local Transp. (Non-TxDOT)</fullName>
                </value>
                <value>
                    <fullName>Maritime/Ports</fullName>
                </value>
                <value>
                    <fullName>Minimum Wage</fullName>
                </value>
                <value>
                    <fullName>OS/OW</fullName>
                </value>
                <value>
                    <fullName>Other (Gen. Gov’t)</fullName>
                </value>
                <value>
                    <fullName>Other (TxDOT)</fullName>
                </value>
                <value>
                    <fullName>Professional Services (Eng.)</fullName>
                </value>
                <value>
                    <fullName>Prop 1/7</fullName>
                </value>
                <value>
                    <fullName>Report/Study</fullName>
                </value>
                <value>
                    <fullName>ROW (Non-ED)</fullName>
                </value>
                <value>
                    <fullName>Rules, PIA, Open Meetings</fullName>
                </value>
                <value>
                    <fullName>SHF</fullName>
                </value>
                <value>
                    <fullName>Special Districts (MUDS)</fullName>
                </value>
                <value>
                    <fullName>Sunset Bills</fullName>
                </value>
                <value>
                    <fullName>TERP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TxDOT Tracked Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TxDOT Tracked Bills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LTA_Bill_Analysis__c.object
<CustomObject>
    <description>Utilized for providing multi-tier analysis for proposed legislative bills.</description>
    <fields>
        <fullName>Bill_Author__c</fullName>
        <formula>Link_to_Bill__r.Bill_Author__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Author</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Caption__c</fullName>
        <formula>Link_to_Bill__r.Bill_Caption__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Caption</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Indicates when the Bill Analysis is due for this Bill Version.</description>
        <inlineHelpText>Indicates when the Bill Analysis is due for this Bill Version.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Bill Analysis</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bill Analysis Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Analyses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LTA_BillImport__c.object
<CustomObject>
    <description>Staging area for imported bill data to allow import logic to be maintained w/in Salesforce.com</description>
    <fields>
        <fullName>Bill_Author__c</fullName>
        <label>Bill Author</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Caption__c</fullName>
        <label>Bill Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Session__c</fullName>
        <label>Bill Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_State__c</fullName>
        <label>Bill State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Type__c</fullName>
        <label>Bill Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_Number__c</fullName>
        <label>CB1 Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_Session__c</fullName>
        <label>CB1 Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_State__c</fullName>
        <label>CB1 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_Type__c</fullName>
        <label>CB1 Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_Number__c</fullName>
        <label>CB2 Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_Session__c</fullName>
        <label>CB2 Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_State__c</fullName>
        <label>CB2 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_Type__c</fullName>
        <label>CB2 Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_Number__c</fullName>
        <label>CB3 Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_Session__c</fullName>
        <label>CB3 Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_State__c</fullName>
        <label>CB3 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_Type__c</fullName>
        <label>CB3 Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCR__c</fullName>
        <label>CCR</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENG__c</fullName>
        <label>ENG</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENR__c</fullName>
        <label>ENR</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FBA__c</fullName>
        <label>FBA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFN__c</fullName>
        <label>FFN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIL__c</fullName>
        <label>FIL</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HBA__c</fullName>
        <label>HBA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCA__c</fullName>
        <label>HCA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCS__c</fullName>
        <label>HCS</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HFA__c</fullName>
        <label>HFA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HFN__c</fullName>
        <label>HFN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HPA__c</fullName>
        <label>HPA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Action__c</fullName>
        <label>Last Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SBA__c</fullName>
        <label>SBA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCA__c</fullName>
        <label>SCA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCS__c</fullName>
        <label>SCS</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFA__c</fullName>
        <label>SFA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFN__c</fullName>
        <label>SFN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPA__c</fullName>
        <label>SPA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VET__c</fullName>
        <label>VET</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Telicon Datum</label>
    <nameField>
        <displayFormat>Raw-{0000000000}</displayFormat>
        <label>Raw Datum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telicon Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LTA_Bill_UnitTests.cls
/******************************************************************************************
 * Name: LTA_Bill_UnitTests
 * @Overall Description: Unit tests for the Bill Import/Processing
 * 
 * @Change Version:        Developer:         Change Date:          Change Description:
 * ----------------------------------------------------------------------------------------
 * 1.0                       VENTAS            2020-08-04             Initial Creation
 *
 ******************************************************************************************
*/
@isTest public class LTA_Bill_UnitTests {
    @isTest
    public static void testTier3() {
        LTA_ProcessTeliconImport batchClass = new LTA_ProcessTeliconImport();

        LTA_BillImport__c b = new LTA_BillImport__c();
        b.Bill__c                    ='TX86RHB00001';
        b.Bill_State__c              ='TX';
        b.Bill_Session__c            ='86R';
        b.Bill_Type__c               ='HB ';
        b.Bill_Number__c             ='1    ';
        b.Bill_Author__c             ='Zerwas, John';
        b.Bill_Caption__c            ='General Appropriations Bill.';
        b.CB1_State__c               ='  ';
        b.CB1_Session__c             ='   ';
        b.CB1_Type__c                ='   ';
        b.CB1_Number__c              ='     ';
        b.CB2_State__c               ='  ';
        b.CB2_Session__c             ='   ';
        b.CB2_Type__c                ='   ';
        b.CB2_Number__c              ='     ';
        b.CB3_State__c               ='  ';
        b.CB3_Session__c             ='   ';
        b.CB3_Type__c                ='   ';
        b.CB3_Number__c              ='     ';
        b.FIL__c                     ='20190123';
        b.HCA__c                     ='        ';
        b.HCS__c                     ='        ';
        b.HFN__c                     ='        ';
        b.HBA__c                     ='        ';
        b.HPA__c                     ='        ';
        b.HFA__c                     ='        ';
        b.ENG__c                     ='        ';
        b.SCA__c                     ='        ';
        b.SCS__c                     ='        ';
        b.SFN__c                     ='        ';
        b.SBA__c                     ='        ';
        b.SPA__c                     ='        ';
        b.SFA__c                     ='        ';
        b.CCR__c                     ='        ';
        b.FBA__c                     ='        ';
        b.FFN__c                     ='        ';
        b.ENR__c                     ='        ';
        b.VET__c                     ='        ';
        b.Last_Action__c             ='09-01-19 G Earliest effective date';
        b.Link__c                    ='https://www.telicon.com/htbin/dil_bill?0120980TX86RHB00001';
        insert b;
        
        test.startTest();
            LTA_ProcessTeliconImport.start();
        test.stopTest();
        
        LTA_Bill__c bill = [SELECT ID, Due_Date__c, Subject__c, Impact__c, Legislative_Liaison_SLA__c, Primary_Division__c, Corollary_Division_s__c FROM LTA_Bill__c WHERE Telicon_Bill_ID__c = :b.Bill__c];
        
        bill.Due_Date__c = date.today().AddDays(5); //Change due date for more coverage
        bill.Subject__c = 'Appropriations';
        bill.Impact__c = '3 - Low';
        bill.Legislative_Liaison_SLA__c = [SELECT Id FROM User WHERE Username='dne3@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com'].Id;
        bill.Primary_Division__c = 'AUD';
        bill.Corollary_Division_s__c = 'AVN';
        update bill;
        
        LTA_Bill_Analysis__c tier3 = new LTA_Bill_Analysis__c();
        tier3.Division_SME_Analysis__c = [SELECT Id FROM LTA_Bill_Analysis__c WHERE Division_SME_Analysis__c=null LIMIT 1].Id;
        tier3.OwnerId = [SELECT Id FROM User WHERE Username='dne4@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com'].Id;
        insert tier3;
        
        tier3 = [SELECT Id, Division_SME_Analysis__c, OwnerId, Owner.IsActive, Link_To_Bill__c FROM LTA_Bill_Analysis__c WHERE Id = :tier3.Id];
        system.debug(tier3);
        system.debug(tier3.Owner);
    }

    @isTest
    public static void test1() {
        LTA_ProcessTeliconImport batchClass = new LTA_ProcessTeliconImport();

        LTA_BillImport__c b = new LTA_BillImport__c();
        b.Bill__c                    ='TX86RHB00001';
        b.Bill_State__c              ='TX';
        b.Bill_Session__c            ='86R';
        b.Bill_Type__c               ='HB ';
        b.Bill_Number__c             ='1    ';
        b.Bill_Author__c             ='Zerwas, John';
        b.Bill_Caption__c            ='General Appropriations Bill.';
        b.CB1_State__c               ='  ';
        b.CB1_Session__c             ='   ';
        b.CB1_Type__c                ='   ';
        b.CB1_Number__c              ='     ';
        b.CB2_State__c               ='  ';
        b.CB2_Session__c             ='   ';
        b.CB2_Type__c                ='   ';
        b.CB2_Number__c              ='     ';
        b.CB3_State__c               ='  ';
        b.CB3_Session__c             ='   ';
        b.CB3_Type__c                ='   ';
        b.CB3_Number__c              ='     ';
        b.FIL__c                     ='20190123';
        b.HCA__c                     ='        ';
        b.HCS__c                     ='        ';
        b.HFN__c                     ='        ';
        b.HBA__c                     ='        ';
        b.HPA__c                     ='        ';
        b.HFA__c                     ='        ';
        b.ENG__c                     ='        ';
        b.SCA__c                     ='        ';
        b.SCS__c                     ='        ';
        b.SFN__c                     ='        ';
        b.SBA__c                     ='        ';
        b.SPA__c                     ='        ';
        b.SFA__c                     ='        ';
        b.CCR__c                     ='        ';
        b.FBA__c                     ='        ';
        b.FFN__c                     ='        ';
        b.ENR__c                     ='        ';
        b.VET__c                     ='        ';
        b.Last_Action__c             ='09-01-19 G Earliest effective date';
        b.Link__c                    ='https://www.telicon.com/htbin/dil_bill?0120980TX86RHB00001';
        insert b;
        
        test.startTest();
            LTA_ProcessTeliconImport.start();
        test.stopTest();
        
        LTA_Bill__c bill = [SELECT ID, Due_Date__c, Subject__c, Impact__c, Legislative_Liaison_SLA__c, Primary_Division__c, Corollary_Division_s__c FROM LTA_Bill__c WHERE Telicon_Bill_ID__c = :b.Bill__c];
        
        bill.Due_Date__c = date.today().AddDays(5); //Change due date for more coverage
        bill.Subject__c = 'Appropriations';
        bill.Impact__c = '3 - Low';
        bill.Legislative_Liaison_SLA__c = [SELECT Id FROM User WHERE Username='dne3@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com'].Id;
        bill.Primary_Division__c = 'AUD';
        bill.Corollary_Division_s__c = 'AVN';
        update bill;
        
        LTA_Bill_Analysis__c tier3 = new LTA_Bill_Analysis__c();
        tier3.Division_SME_Analysis__c = [SELECT Id FROM LTA_Bill_Analysis__c WHERE Division_SME_Analysis__c=null LIMIT 1].Id;
        tier3.OwnerId = [SELECT Id FROM User WHERE Username='dne4@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com'].Id;
        insert tier3;

        b.Id = null; //Process same data...
        insert b;
        //Manually call batch methods this round...
        batchClass.execute(null, [SELECT Id, OwnerId, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, Bill_State__c, Bill_Session__c, Bill_Type__c, Bill_Number__c, Bill__c, Bill_Author__c, Bill_Caption__c, Bill_f__c, Last_Action__c, CB1_State__c, CB2_State__c, CB3_State__c, CB1_Session__c, CB2_Session__c, CB3_Session__c, CB1_Type__c, CB2_Type__c, CB3_Type__c, CB1_Number__c, CB2_Number__c, CB3_Number__c, CB1_f__c, CB2_f__c, CB3_f__c, Processed__c, Link__c, FIL__c, HCA__c, HCS__c, HFN__c, HBA__c, HPA__c, HFA__c, ENG__c, SCA__c, SCS__c, SFN__c, SBA__c, SPA__c, SFA__c, CCR__c, FBA__c, FFN__c, ENR__c, VET__c FROM LTA_BillImport__c WHERE Processed__c=null ORDER BY CreatedDate ASC]);

        
        b = new LTA_BillImport__c();
        b.Bill__c                    ='TX86RHB00001';
        b.Bill_State__c              ='TX';
        b.Bill_Session__c            ='86R';
        b.Bill_Type__c               ='HB ';
        b.Bill_Number__c             ='1    ';
        b.Bill_Author__c             ='Zerwas, John';
        b.Bill_Caption__c            ='General Appropriations Bill.';
        b.CB1_State__c               ='  ';
        b.CB1_Session__c             ='   ';
        b.CB1_Type__c                ='   ';
        b.CB1_Number__c              ='     ';
        b.CB2_State__c               ='  ';
        b.CB2_Session__c             ='   ';
        b.CB2_Type__c                ='   ';
        b.CB2_Number__c              ='     ';
        b.CB3_State__c               ='  ';
        b.CB3_Session__c             ='   ';
        b.CB3_Type__c                ='   ';
        b.CB3_Number__c              ='     ';
        b.FIL__c                     ='20190123';
        b.HCA__c                     ='        ';
        b.HCS__c                     ='20190318';
        b.HFN__c                     ='        ';
        b.HBA__c                     ='        ';
        b.HPA__c                     ='        ';
        b.HFA__c                     ='        ';
        b.ENG__c                     ='        ';
        b.SCA__c                     ='        ';
        b.SCS__c                     ='        ';
        b.SFN__c                     ='        ';
        b.SBA__c                     ='        ';
        b.SPA__c                     ='        ';
        b.SFA__c                     ='        ';
        b.CCR__c                     ='        ';
        b.FBA__c                     ='        ';
        b.FFN__c                     ='        ';
        b.ENR__c                     ='        ';
        b.VET__c                     ='        ';
        b.Last_Action__c             ='09-01-19 G Earliest effective date';
        b.Link__c                    ='https://www.telicon.com/htbin/dil_bill?0120980TX86RHB00001';
        insert b;
        
        //Manually call batch methods this round...
        batchClass.execute(null, [SELECT Id, OwnerId, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, Bill_State__c, Bill_Session__c, Bill_Type__c, Bill_Number__c, Bill__c, Bill_Author__c, Bill_Caption__c, Bill_f__c, Last_Action__c, CB1_State__c, CB2_State__c, CB3_State__c, CB1_Session__c, CB2_Session__c, CB3_Session__c, CB1_Type__c, CB2_Type__c, CB3_Type__c, CB1_Number__c, CB2_Number__c, CB3_Number__c, CB1_f__c, CB2_f__c, CB3_f__c, Processed__c, Link__c, FIL__c, HCA__c, HCS__c, HFN__c, HBA__c, HPA__c, HFA__c, ENG__c, SCA__c, SCS__c, SFN__c, SBA__c, SPA__c, SFA__c, CCR__c, FBA__c, FFN__c, ENR__c, VET__c FROM LTA_BillImport__c WHERE Processed__c=null ORDER BY CreatedDate ASC]);
        
        bill.Due_Date__c = date.today().AddDays(15); //Change due date for more coverage
        update bill;

        b = new LTA_BillImport__c();
        b.Bill__c                    ='TX86RHB00001';
        b.Bill_State__c              ='TX';
        b.Bill_Session__c            ='86R';
        b.Bill_Type__c               ='HB ';
        b.Bill_Number__c             ='1    ';
        b.Bill_Author__c             ='Zerwas, John';
        b.Bill_Caption__c            ='General Appropriations Bill.';
        b.CB1_State__c               ='  ';
        b.CB1_Session__c             ='   ';
        b.CB1_Type__c                ='   ';
        b.CB1_Number__c              ='     ';
        b.CB2_State__c               ='  ';
        b.CB2_Session__c             ='   ';
        b.CB2_Type__c                ='   ';
        b.CB2_Number__c              ='     ';
        b.CB3_State__c               ='  ';
        b.CB3_Session__c             ='   ';
        b.CB3_Type__c                ='   ';
        b.CB3_Number__c              ='     ';
        b.FIL__c                     ='20190123';
        b.HCA__c                     ='        ';
        b.HCS__c                     ='20190318';
        b.HFN__c                     ='        ';
        b.HBA__c                     ='        ';
        b.HPA__c                     ='        ';
        b.HFA__c                     ='20190327';
        b.ENG__c                     ='20190328';
        b.SCA__c                     ='        ';
        b.SCS__c                     ='20190403';
        b.SFN__c                     ='        ';
        b.SBA__c                     ='        ';
        b.SPA__c                     ='        ';
        b.SFA__c                     ='        ';
        b.CCR__c                     ='20190525';
        b.FBA__c                     ='        ';
        b.FFN__c                     ='        ';
        b.ENR__c                     ='20190527';
        b.VET__c                     ='        ';
        b.Last_Action__c             ='09-01-19 G Earliest effective date';
        b.Link__c                    ='https://www.telicon.com/htbin/dil_bill?0120980TX86RHB00001';
        insert b;

        //Manually call batch methods this round...
        batchClass.execute(null, [SELECT Id, OwnerId, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, Bill_State__c, Bill_Session__c, Bill_Type__c, Bill_Number__c, Bill__c, Bill_Author__c, Bill_Caption__c, Bill_f__c, Last_Action__c, CB1_State__c, CB2_State__c, CB3_State__c, CB1_Session__c, CB2_Session__c, CB3_Session__c, CB1_Type__c, CB2_Type__c, CB3_Type__c, CB1_Number__c, CB2_Number__c, CB3_Number__c, CB1_f__c, CB2_f__c, CB3_f__c, Processed__c, Link__c, FIL__c, HCA__c, HCS__c, HFN__c, HBA__c, HPA__c, HFA__c, ENG__c, SCA__c, SCS__c, SFN__c, SBA__c, SPA__c, SFA__c, CCR__c, FBA__c, FFN__c, ENR__c, VET__c FROM LTA_BillImport__c WHERE Processed__c=null ORDER BY CreatedDate ASC]);
    }

    @testsetup
    public static void setupTest() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'TxDOT Basic Profile'];
        
        List<User> users = new List<User>();
        User u = new User();
        u.Division__c = 'AUD';
        u.LastName = 'XXX';
        u.Username = 'dne1@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com';
        u.Email = 'test@testing.com';
        u.Alias = '123124';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey ='America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.IsActive = true;
        u.Title__c = 'Legislative Coordinator';
        users.add(u);

        u = new User();        
        u.Division__c = 'AVN';
        u.LastName = 'XXX';
        u.Username = 'dne2@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com';
        u.Email = 'test@testing.com';
        u.Alias = '123124';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey ='America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.IsActive = true;
        u.Title__c = 'Legislative Coordinator';
        users.add(u);
        
        u = new User();
        u.Division__c = 'SLA';
        u.LastName = 'XXX';
        u.Username = 'dne3@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com';
        u.Email = 'test@testing.com';
        u.Alias = '123124';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey ='America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.IsActive = true;
        users.add(u);

        u = new User();
        u.Division__c = 'ITD';
        u.LastName = 'XXX';
        u.Username = 'dne4@lsadjkhfladsjkhflsadhflsadjkhfalsdjkfhalsdjkhasdf.com';
        u.Email = 'test@testing.com';
        u.Alias = '123124';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey ='America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.IsActive = true;
        users.add(u);
        
        insert users;
        
    }
}