src/objects/LTA_Bill__c.object
<CustomObject>
    <description>This object houses all Legislative Bill data from Telicon.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Indicates when the Final Analysis is due for this Bill Version.</description>
        <inlineHelpText>Indicates when the Final Analysis is due for this Bill Version.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>TxDOT Tracked Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TxDOT Tracked Bills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LTA_Bill_Analysis__c.object
<CustomObject>
    <description>Utilized for providing multi-tier analysis for proposed legislative bills.</description>
    <fields>
        <fullName>Division_SME_Analysis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the list of Division SME Bill Analysis  (Tier C) records.</description>
        <inlineHelpText>Provides the list of Division SME Bill Analysis records.</inlineHelpText>
        <label>Division SME Analysis</label>
        <referenceTo>LTA_Bill_Analysis__c</referenceTo>
        <relationshipLabel>Division SME Analysis</relationshipLabel>
        <relationshipName>Bill_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Indicates when the Bill Analysis is due for this Bill Version.</description>
        <inlineHelpText>Indicates when the Bill Analysis is due for this Bill Version.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Link_to_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link to Bill</label>
        <referenceTo>LTA_Bill__c</referenceTo>
        <relationshipLabel>Bill Analyses</relationshipLabel>
        <relationshipName>Bill_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <description>Indicates what stage the Bill Analysis is in.</description>
        <label>Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bill Analysis</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bill Analysis Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Analyses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LTA_Bill_Analysis_TriggerHandler.cls
/******************************************************************************************
 * Name: LTA_Bill_Analysis_TriggerHandler
 * @Overall Description: Trigger handler for the Bill Analysis creations and assignments.
 * Identifies Tier A, B and C users while assigning Due Dates.
 * 
 * @Change Version:        Developer:         Change Date:          Change Description:
 * ----------------------------------------------------------------------------------------
 * 1.0                       VENTAS            2020-08-04            Initial Creation
 *
 ******************************************************************************************
*/

public without sharing class LTA_Bill_Analysis_TriggerHandler {
    public static void Process(){
        if (trigger.isbefore && trigger.isInsert) {
            Set<Id> tierB_Ids = new Set<Id>();
           
            for(LTA_Bill_Analysis__c ba : (List<LTA_Bill_Analysis__c>) trigger.new){
                if(ba.Division_SME_Analysis__c != null){
                    tierB_Ids.add(ba.Division_SME_Analysis__c);
                }
            }
            
            if(!tierB_Ids.isEmpty()){
                Map<Id, LTA_Bill_Analysis__c> tierB_Map = new Map<Id, LTA_Bill_Analysis__c>([SELECT Id, Link_To_Bill__c, Link_To_Bill__r.Due_Date__c FROM LTA_Bill_Analysis__c WHERE Id IN :tierB_Ids]);
                
                for(LTA_Bill_Analysis__c tierC : (LTA_Bill_Analysis__c[]) trigger.new) {
                    if (tierB_Map.containsKey(tierC.Division_SME_Analysis__c)) {
                        LTA_Bill_Analysis__c tierB = tierB_Map.get(tierC.Division_SME_Analysis__c);
                        if (tierB.Link_To_Bill__c!=null) {
                            //OwnerId = ;
                            tierC.Review_Status__c = 'New';
                            tierC.Link_To_Bill__c = tierB.Link_To_Bill__c;
                            if (tierB.Link_To_Bill__r.Due_Date__c!=null) {
                                tierC.Due_Date__c = tierB.Link_To_Bill__r.Due_Date__c.addDays(LTA_ProcessTeliconImport.tierC_dueDays - LTA_ProcessTeliconImport.tierA_dueDays);
                            }
                        }
                    }
                }
            }
        }
    }
}