src/objects/LTA_Bill__c.object
<CustomObject>
    <description>This object houses all Legislative Bill data from Telicon.</description>
    <fields>
        <fullName>Corollary_Division_s__c</fullName>
        <description>Indicates which Division(s) has secondary responsibility for this bill.</description>
        <inlineHelpText>Indicates which Division(s) has secondary responsibility for this bill.</inlineHelpText>
        <label>Corollary Division(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>AVN</fullName>
                </value>
                <value>
                    <fullName>BRG</fullName>
                </value>
                <value>
                    <fullName>CIV</fullName>
                </value>
                <value>
                    <fullName>CMD</fullName>
                </value>
                <value>
                    <fullName>CMP</fullName>
                </value>
                <value>
                    <fullName>CSD</fullName>
                </value>
                <value>
                    <fullName>CST</fullName>
                </value>
                <value>
                    <fullName>DES</fullName>
                </value>
                <value>
                    <fullName>ENV</fullName>
                </value>
                <value>
                    <fullName>FED</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>FOD</fullName>
                </value>
                <value>
                    <fullName>GCD</fullName>
                </value>
                <value>
                    <fullName>HRD</fullName>
                </value>
                <value>
                    <fullName>ITD</fullName>
                </value>
                <value>
                    <fullName>MNT</fullName>
                </value>
                <value>
                    <fullName>MRD</fullName>
                </value>
                <value>
                    <fullName>MTD</fullName>
                </value>
                <value>
                    <fullName>OCC</fullName>
                </value>
                <value>
                    <fullName>PEPS</fullName>
                </value>
                <value>
                    <fullName>PFD</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>PTN</fullName>
                </value>
                <value>
                    <fullName>ROW</fullName>
                </value>
                <value>
                    <fullName>RRD</fullName>
                </value>
                <value>
                    <fullName>RTI</fullName>
                </value>
                <value>
                    <fullName>SLA</fullName>
                </value>
                <value>
                    <fullName>SSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Indicates when the Final Analysis is due for this Bill Version.</description>
        <inlineHelpText>Indicates when the Final Analysis is due for this Bill Version.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legislative_Liaison_SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the Tier A User assignment for this bill.</description>
        <inlineHelpText>The assigned Legislative Liaison responsible for the final analysis of this Bill Version.</inlineHelpText>
        <label>SLA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the appropriate SLA user.</errorMessage>
            <filterItems>
                <field>User.Division__c</field>
                <operation>equals</operation>
                <value>SLA</value>
            </filterItems>
            <filterItems>
                <field>$Source.Subject__c</field>
                <operation>notEqual</operation>
                <value>null</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>LTA_Bill__c</referenceTo>
        <relationshipName>Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Division__c</fullName>
        <description>Indicates which Division has the primary responsibility for this bill.</description>
        <inlineHelpText>Indicates which Division has the primary responsibility for this bill.</inlineHelpText>
        <label>Primary Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Analysis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup will allow for auto-creation of the Tier A SLA Bill Analysis.</description>
        <label>SLA Analysis</label>
        <referenceTo>LTA_Bill_Analysis__c</referenceTo>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TxDOT Tracked Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TxDOT Tracked Bills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LTA_Bill_Analysis__c.object
<CustomObject>
    <description>Utilized for providing multi-tier analysis for proposed legislative bills.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Tier User assigned</inlineHelpText>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bill_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corollary_Division_s__c</fullName>
        <description>Populated by the LTA - Bill Analysis Automation process builder.</description>
        <label>Corollary Division(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_SME_Analysis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provides the list of Division SME Bill Analysis  (Tier C) records.</description>
        <inlineHelpText>Provides the list of Division SME Bill Analysis records.</inlineHelpText>
        <label>Division SME Analysis</label>
        <referenceTo>LTA_Bill_Analysis__c</referenceTo>
        <relationshipLabel>Division SME Analysis</relationshipLabel>
        <relationshipName>Bill_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>Owner:User.Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Indicates when the Bill Analysis is due for this Bill Version.</description>
        <inlineHelpText>Indicates when the Bill Analysis is due for this Bill Version.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Link_to_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link to Bill</label>
        <referenceTo>LTA_Bill__c</referenceTo>
        <relationshipLabel>Bill Analyses</relationshipLabel>
        <relationshipName>Bill_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Division__c</fullName>
        <formula>TEXT(Link_to_Bill__r.Primary_Division__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <description>Indicates what stage the Bill Analysis is in.</description>
        <label>Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Owner:User.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Bill Analysis</label>
    <nameField>
        <displayFormat>BA-{00000000}</displayFormat>
        <label>Bill Analysis Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Analyses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <description>This will be used for users with project/app-specific divisions.</description>
        <inlineHelpText>This will be used for users with project/app-specific divisions.</inlineHelpText>
        <label>Division</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>This will be used for users with project/app-specific titles.</description>
        <inlineHelpText>This will be used for users with project/app-specific titles.</inlineHelpText>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SLA Only</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AVN</fullName>
    </customValue>
    <customValue>
        <fullName>BRG</fullName>
    </customValue>
    <customValue>
        <fullName>CIV</fullName>
    </customValue>
    <customValue>
        <fullName>CMD</fullName>
    </customValue>
    <customValue>
        <fullName>CMP</fullName>
    </customValue>
    <customValue>
        <fullName>CSD</fullName>
    </customValue>
    <customValue>
        <fullName>CST</fullName>
    </customValue>
    <customValue>
        <fullName>DES</fullName>
    </customValue>
    <customValue>
        <fullName>ENV</fullName>
    </customValue>
    <customValue>
        <fullName>FED</fullName>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
    </customValue>
    <customValue>
        <fullName>FOD</fullName>
    </customValue>
    <customValue>
        <fullName>GCD</fullName>
    </customValue>
    <customValue>
        <fullName>HRD</fullName>
    </customValue>
    <customValue>
        <fullName>ITD</fullName>
    </customValue>
    <customValue>
        <fullName>MNT</fullName>
    </customValue>
    <customValue>
        <fullName>MRD</fullName>
    </customValue>
    <customValue>
        <fullName>MTD</fullName>
    </customValue>
    <customValue>
        <fullName>OCC</fullName>
    </customValue>
    <customValue>
        <fullName>PEPS</fullName>
    </customValue>
    <customValue>
        <fullName>PFD</fullName>
    </customValue>
    <customValue>
        <fullName>PRO</fullName>
    </customValue>
    <customValue>
        <fullName>PTN</fullName>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
    </customValue>
    <customValue>
        <fullName>RRD</fullName>
    </customValue>
    <customValue>
        <fullName>RTI</fullName>
    </customValue>
    <customValue>
        <fullName>SLA</fullName>
    </customValue>
    <customValue>
        <fullName>SSD</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

src/classes/LTA_Bill_TriggerHandler.cls
/******************************************************************************************
 * Name: LTA_Bill_TriggerHandler
 * @Overall Description: Keep due dates in sync with LTA_Bill_Analysis__c records when changed on an bill record
 *      When a new bill is inserted, link to the previous bill
 *      If 4 specific fields are populated, and LTA_Bill_Analysis__c records do not exist, generate LTA_Bill_Analysis__c records for the SLA, Primary and Corollary division users.
 * 
 * @Change Version:        Developer:         Change Date:          Change Description:
 * ----------------------------------------------------------------------------------------
 * 1.0                       VENTAS            2020-08-04            Initial Creation
 *
 ******************************************************************************************
*/

public without sharing class LTA_Bill_TriggerHandler {
    private static void updateDueDates(List<LTA_Bill__c> triggerNew, Map<Id,LTA_Bill__c> triggerOldMap){
        List<Id> ids = new List<Id>();
        for(LTA_Bill__c bill : triggerNew){
            //if this is supposed to cover only due date changes, I think it should not execute if Due Date is changing from null to not null
            if(triggerOldMap.get(bill.Id).Due_Date__c != null && bill.Due_Date__c != triggerOldMap.get(bill.Id).Due_Date__c) {
                ids.add(bill.Id);
            }
        }
        
        if(!ids.isEmpty()) {
            List<LTA_Bill_Analysis__c> listUpdates = new List<LTA_Bill_Analysis__c>();
            for(LTA_Bill__c b : [SELECT Id, OwnerId, Legislative_Liaison_SLA__c, SLA_Analysis__c, Due_Date__c, (SELECT Id, OwnerId, Due_Date__c, Division_SME_Analysis__c FROM Bill_Analyses__r) FROM LTA_Bill__c WHERE Id IN :ids]) {
                if (!b.Bill_Analyses__r.isEmpty()) {
                    for(LTA_Bill_Analysis__c ba : b.Bill_Analyses__r) {
                        if(ba.OwnerId == b.Legislative_Liaison_SLA__c) //Tier A
                            ba.Due_Date__c = b.Due_Date__c;
                        else if(ba.OwnerId != b.Legislative_Liaison_SLA__c && ba.Division_SME_Analysis__c == null) //Tier B
                            ba.Due_Date__c = b.Due_Date__c.addDays(LTA_ProcessTeliconImport.tierB_dueDays - LTA_ProcessTeliconImport.tierA_dueDays);
                        else { //Tier C
                            ba.Due_Date__c = b.Due_Date__c.addDays(LTA_ProcessTeliconImport.tierC_dueDays - LTA_ProcessTeliconImport.tierA_dueDays);
                        }
                        listUpdates.add(ba);
                    }
                }
            }
           
            update listUpdates;
        }
    }

    private static void afterInsertUpdateHandler(){
        system.debug('BEGIN afterInsertUpdateHandler()');
        
        set<Id> parentIds = new set<Id>();
        List<LTA_Bill__c> billsToProcess = new List<LTA_Bill__c>();
        for(LTA_Bill__c bill : [SELECT Id, OwnerId, Parent__c, Primary_Division__c, Corollary_Division_s__c, Legislative_Liaison_SLA__c, SLA_Analysis__c, Due_Date__c, (SELECT Id, OwnerId, Owner.Username, Due_Date__c, Division_SME_Analysis__c FROM Bill_Analyses__r) FROM LTA_Bill__c WHERE Id IN :trigger.new]){
            //system.debug('Loop Bill: ' + bill);
            //system.debug('Bill.Bill_Analyses__r: ' + bill.Bill_Analyses__r);
            //system.debug('Bill.Bill_Analyses__r.isEmpty(): ' + bill.Bill_Analyses__r.isEmpty());
            if (bill.Bill_Analyses__r.isEmpty()) {
                billsToProcess.add(bill);
                if (bill.Parent__c!=null) {
                    parentIds.add(bill.Parent__c);
                }
            }
        }
        system.debug('parentIds: ' + parentIds);
        system.debug('billsToProcess: ' + billsToProcess);
        
        if (billsToProcess.isEmpty()) {
            system.debug('No bills to process...');
            return;
        }

        Set<String> divisionValues = new Set<String>();
        for(LTA_Bill__c bill : billsToProcess){
            if(bill.Primary_Division__c != null) {
                divisionValues.add(bill.Primary_Division__c);
            }
            if(bill.Corollary_Division_s__c != null) {
                for(String s : bill.Corollary_Division_s__c.split(';')){
                    if (!string.isBlank(s)) {
                        divisionValues.add(s.trim());
                    }
                }
            }
        }
        
        system.debug('divisionValues: ' + divisionValues);

        Map<String, List<User>> divisionToUserMap = new Map<String, List<User>>();
        for(User u : [SELECT Id, Division__c, Title__c FROM User WHERE IsActive=true AND Division__c IN :divisionValues]){
            if(!divisionToUserMap.containsKey(u.Division__c)) {
                divisionToUserMap.put(u.Division__c, new List<User>());
            }
            divisionToUserMap.get(u.Division__c).add(u);
        }

        Map<Id, LTA_Bill__c> previousBills = new Map<Id, LTA_Bill__c> ([SELECT Id, OwnerId, Primary_Division__c, Corollary_Division_s__c, Legislative_Liaison_SLA__c, SLA_Analysis__c, Due_Date__c, (SELECT Id, OwnerId, Owner.IsActive, Division_SME_Analysis__c FROM Bill_Analyses__r) FROM LTA_Bill__c WHERE Id IN :parentIds]);
        system.debug('previousBills: ' + previousBills);
        
        List<LTA_Bill_Analysis__c> basToInsert = new List<LTA_Bill_Analysis__c>();
        List<LTA_Bill_Analysis__c> tierCToInsert = new List<LTA_Bill_Analysis__c>();
        Map<Id, LTA_Bill_Analysis__c> billToSLAAnalysis = new Map<Id, LTA_Bill_Analysis__c>();
        for(LTA_Bill__c bill : billsToProcess){
            //system.debug('bill: ' + bill);
            if(bill.Corollary_Division_s__c != null && bill.Primary_Division__c != null && bill.Legislative_Liaison_SLA__c != null && bill.Due_Date__c!=null){
                Set<String> divisionsToProcess = new Set<String>();
                for(String s : bill.Corollary_Division_s__c.split(';')){
                    if (!string.isBlank(s)) {
                        divisionsToProcess.add(s.trim());
                    }
                }
                divisionsToProcess.add(bill.Primary_Division__c);
                //system.debug('divisionsToProcess: ' + divisionsToProcess);
                
                Map<Id, User> usersToProcess = new Map<Id, User>();
                for(String s : divisionsToProcess){
                    if (divisionToUserMap.containsKey(s)) {
                        //Add Tier-B users. NOTE: There is only 1 per division, but this should handle all for future changes.
                        for(User u : divisionToUserMap.get(s)) {
                            if (u.Title__c == 'Legislative Coordinator') {
                                //Only users w/ this title are Tier-B users.
                                usersToProcess.put(u.Id, u);
                            }
                        }
                    }
                }
                
                //Add the SLA user
                if (!usersToProcess.containsKey(bill.Legislative_Liaison_SLA__c)){
                    usersToProcess.put(bill.Legislative_Liaison_SLA__c, new User(Id = bill.Legislative_Liaison_SLA__c));
                }
                
                for(User u : usersToProcess.values()){
                    //system.debug('user: ' + u);
                    LTA_Bill_Analysis__c newBA = new LTA_Bill_Analysis__c(
                        OwnerId = u.Id,
                        Link_To_Bill__c = bill.Id,
                        Review_Status__c = 'New'
                    );
                    
                    if(u.Id == bill.Legislative_Liaison_SLA__c){
                        billToSLAAnalysis.put(bill.Id, newBA);
                        newBA.Due_Date__c = bill.Due_Date__c;
                    }
                    else {
                        newBA.Due_Date__c = bill.Due_Date__c.addDays(LTA_ProcessTeliconImport.tierB_dueDays - LTA_ProcessTeliconImport.tierA_dueDays);
                    }
                    
                    basToInsert.add(newBA);
                    
                    if (bill.Parent__c != null) {
                        //system.debug('bill.Parent__c: ' + bill.Parent__c);
                        
                        if (previousBills.containsKey(bill.Parent__c)){
                            LTA_Bill__c pb = previousBills.get(bill.Parent__c);
                            //system.debug('pb.Bill_Analyses__r: ' + pb.Bill_Analyses__r);

                            for(LTA_Bill_Analysis__c tierB : pb.Bill_Analyses__r) {
                                if (tierB.Division_SME_Analysis__c!=null) {
                                    //Skip tierB
                                    continue;
                                }
                                
                                if (u.Id != tierB.OwnerId) {
                                    continue;
                                }
                                
                                for(LTA_Bill_Analysis__c tierC : pb.Bill_Analyses__r) {
                                    if (tierC.Division_SME_Analysis__c == tierB.Id) {
                                        if (tierC.Owner.IsActive) {
                                            LTA_Bill_Analysis__c newTierCBA = new LTA_Bill_Analysis__c(
                                                OwnerId = tierC.OwnerId,
                                                Link_to_Bill__c = bill.Id,
                                                Review_Status__c = 'New',
                                                Due_Date__c = bill.Due_Date__c.addDays(LTA_ProcessTeliconImport.tierB_dueDays - LTA_ProcessTeliconImport.tierA_dueDays),
                                                Division_SME_Analysis__r = newBA
                                            );
                                            tierCToInsert.add(newTierCBA);
                                        }
                                        //continue in case there are duplicates...
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        insert basToInsert;

        for(LTA_Bill_Analysis__c ba : tierCToInsert){
            ba.Division_SME_Analysis__c = ba.Division_SME_Analysis__r.Id;
        } 
        insert tierCToInsert;

        //Link the SLA's Bill Analysis back to the parent Bill
        List<LTA_Bill__c> billsToUpdate = new List<LTA_Bill__c>();
        for(string key : billToSLAAnalysis.keySet()){
            billsToUpdate.add(new LTA_Bill__c(Id = key, SLA_Analysis__c = billToSLAAnalysis.get(key).Id));
        }        
        update billsToUpdate;
    }
    
    private static boolean lock = false;
    public static void Process(){
        system.debug('LTA_Bill_TriggerHandler Processing...');
        if (lock) {return;}
        if (trigger.isAfter) {
            if (trigger.isInsert){
                try{
                    lock = true;
                    afterInsertUpdateHandler();
                }
                finally {
                    lock = false;
                }
            }
            else if (trigger.isUpdate) {
                try{
                    lock = true;
                    updateDueDates((List<LTA_Bill__c>)trigger.New, (Map<ID, LTA_Bill__c>)trigger.OldMap);
                }
                finally {
                    lock = false;
                }
                try{
                    lock = true;
                    afterInsertUpdateHandler();
                }
                finally {
                    lock = false;
                }
            }
        }
    }
}