src/objects/LTA_Bill__c.object
<CustomObject>
    <description>This object houses all Legislative Bill data from Telicon.</description>
    <fields>
        <fullName>Bill_Author__c</fullName>
        <label>Bill Author</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Caption__c</fullName>
        <description>Brief summary of the proposed bill.</description>
        <inlineHelpText>Read-only official caption, automatically updated providing a brief summary of the proposed bill.</inlineHelpText>
        <label>Bill Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Session__c</fullName>
        <label>Bill Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Type__c</fullName>
        <description>Indicated Session Number for this Bill Version.</description>
        <inlineHelpText>Indicated Session Number for this Bill Version.</inlineHelpText>
        <label>Bill Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Version__c</fullName>
        <description>Up to 6 versions from the Telicon data feed record.</description>
        <label>Bill Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FIL</fullName>
                    <label>1 - Filed</label>
                </value>
                <value>
                    <fullName>HCS</fullName>
                    <label>2 - House Committee Substitute</label>
                </value>
                <value>
                    <fullName>ENG</fullName>
                    <label>3 - Engrossed</label>
                </value>
                <value>
                    <fullName>SCS</fullName>
                    <label>4 - Senate Committee Substitute</label>
                </value>
                <value>
                    <fullName>CCR</fullName>
                    <label>5 - Conference Committee Report</label>
                </value>
                <value>
                    <fullName>ENR</fullName>
                    <label>6 - As Finally Passed (Enrolled)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <description>Indicates the proposed bill&apos;s impact categorization.</description>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Significant</fullName>
                </value>
                <value>
                    <fullName>2 - Moderate</fullName>
                </value>
                <value>
                    <fullName>3 - Low</fullName>
                </value>
                <value>
                    <fullName>4 - No Direct Impact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Action__c</fullName>
        <description>Indicates the last action on the Bill within Telicon.</description>
        <inlineHelpText>Indicates the last action on the Bill within Telicon.</inlineHelpText>
        <label>Last Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Telicon (TLO) Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Indicates the proposed bill&apos;s subject categorization.</description>
        <label>TxDOT Subject Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appropriations</fullName>
                </value>
                <value>
                    <fullName>Bike/Ped</fullName>
                </value>
                <value>
                    <fullName>Construction/Letting</fullName>
                </value>
                <value>
                    <fullName>Contracting (Goods &amp; Non.Prof. Services)</fullName>
                </value>
                <value>
                    <fullName>DB/CDA</fullName>
                </value>
                <value>
                    <fullName>Eminent Domain</fullName>
                </value>
                <value>
                    <fullName>Energy Sector</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (Funding - CDL)</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (Funding - Traffic Safety)</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (OS/OW)</fullName>
                </value>
                <value>
                    <fullName>Federal Compliance (Other)</fullName>
                </value>
                <value>
                    <fullName>High-Speed Rail</fullName>
                </value>
                <value>
                    <fullName>Highway Memorial Designation</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Local Transp. (Non-TxDOT)</fullName>
                </value>
                <value>
                    <fullName>Maritime/Ports</fullName>
                </value>
                <value>
                    <fullName>Minimum Wage</fullName>
                </value>
                <value>
                    <fullName>OS/OW</fullName>
                </value>
                <value>
                    <fullName>Other (Gen. Gov’t)</fullName>
                </value>
                <value>
                    <fullName>Other (TxDOT)</fullName>
                </value>
                <value>
                    <fullName>Professional Services (Eng.)</fullName>
                </value>
                <value>
                    <fullName>Prop 1/7</fullName>
                </value>
                <value>
                    <fullName>Report/Study</fullName>
                </value>
                <value>
                    <fullName>ROW (Non-ED)</fullName>
                </value>
                <value>
                    <fullName>Rules, PIA, Open Meetings</fullName>
                </value>
                <value>
                    <fullName>SHF</fullName>
                </value>
                <value>
                    <fullName>Special Districts (MUDS)</fullName>
                </value>
                <value>
                    <fullName>Sunset Bills</fullName>
                </value>
                <value>
                    <fullName>TERP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Telicon_Bill_ID__c</fullName>
        <description>External ID for the Telicon data feed</description>
        <externalId>true</externalId>
        <label>Telicon Bill ID</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>TxDOT Tracked Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TxDOT Tracked Bills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LTA_BillImport__c.object
<CustomObject>
    <description>Staging area for imported bill data to allow import logic to be maintained w/in Salesforce.com</description>
    <fields>
        <fullName>Bill_Author__c</fullName>
        <label>Bill Author</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Caption__c</fullName>
        <label>Bill Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Session__c</fullName>
        <label>Bill Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_State__c</fullName>
        <label>Bill State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Type__c</fullName>
        <label>Bill Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_f__c</fullName>
        <formula>Bill_State__c+Bill_Session__c+Bill_Type__c+LPAD(TRIM(Bill_Number__c), 5, &apos;0&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_Number__c</fullName>
        <label>CB1 Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_Session__c</fullName>
        <label>CB1 Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_State__c</fullName>
        <label>CB1 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_Type__c</fullName>
        <label>CB1 Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB1_f__c</fullName>
        <formula>CB1_State__c+CB1_Session__c+CB1_Type__c+LPAD(TRIM(CB1_Number__c), 5, &apos;0&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CB1 Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_Number__c</fullName>
        <label>CB2 Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_Session__c</fullName>
        <label>CB2 Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_State__c</fullName>
        <label>CB2 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_Type__c</fullName>
        <label>CB2 Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB2_f__c</fullName>
        <formula>CB2_State__c+CB2_Session__c+CB2_Type__c+LPAD(TRIM(CB2_Number__c), 5, &apos;0&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CB2 Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_Number__c</fullName>
        <label>CB3 Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_Session__c</fullName>
        <label>CB3 Session</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_State__c</fullName>
        <label>CB3 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_Type__c</fullName>
        <label>CB3 Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CB3_f__c</fullName>
        <formula>CB3_State__c+CB3_Session__c+CB3_Type__c+LPAD(TRIM(CB3_Number__c), 5, &apos;0&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CB3_Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCR__c</fullName>
        <label>CCR</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENG__c</fullName>
        <label>ENG</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENR__c</fullName>
        <label>ENR</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FBA__c</fullName>
        <label>FBA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFN__c</fullName>
        <label>FFN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIL__c</fullName>
        <label>FIL</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HBA__c</fullName>
        <label>HBA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCA__c</fullName>
        <label>HCA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCS__c</fullName>
        <label>HCS</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HFA__c</fullName>
        <label>HFA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HFN__c</fullName>
        <label>HFN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HPA__c</fullName>
        <label>HPA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Action__c</fullName>
        <label>Last Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <description>Date data was processed</description>
        <label>Processed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SBA__c</fullName>
        <label>SBA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCA__c</fullName>
        <label>SCA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCS__c</fullName>
        <label>SCS</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFA__c</fullName>
        <label>SFA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFN__c</fullName>
        <label>SFN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPA__c</fullName>
        <label>SPA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VET__c</fullName>
        <label>VET</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Telicon Datum</label>
    <nameField>
        <displayFormat>Raw-{0000000000}</displayFormat>
        <label>Raw Datum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telicon Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LTA_ProcessTeliconImport.cls
/******************************************************************************************
 * Name: LTA_ProcessTeliconImport
 * @Overall Description: Batch data load process and mapping for data from Telicon into LTA_BillImport__c object. 
 *  This process loads the raw data into the LTA_BillImport__c object then identifies the specific TxDOT LTA versions 
 *  and automatically maps into the LTA_Bill__c object while carrying over previous data points if a new Bill Version 
 *  is loaded and automatically assigning associated Due Dates.
 * 
 * @Change Version:        Developer:         Change Date:          Change Description:
 * ----------------------------------------------------------------------------------------
 * 1.0                       VENTAS            2020-08-04             Initial Creation
 *
 ******************************************************************************************
*/
public without sharing class LTA_ProcessTeliconImport implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    public static final integer tierA_dueDays = 7;
    public static final integer tierB_dueDays = 5;
    public static final integer tierC_dueDays = 3;

    private final DateTime batchTimeStamp = DateTime.now(); //Use this GMT timstamp for marking processed records w/ same exact value
    private final Date batchToday = Date.today();

    public void execute(SchedulableContext sc) {
        start();
    }
    
    public static void start() {
        start(100);
    }
    
    public static void start(integer batchSize) {
        database.executeBatch(new LTA_ProcessTeliconImport(), batchSize);
    }

    public LTA_ProcessTeliconImport() {

    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT
                Id,
                OwnerId,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                Bill_State__c,
                Bill_Session__c,
                Bill_Type__c,
                Bill_Number__c,
                Bill__c,
                Bill_Author__c,
                Bill_Caption__c,
                Bill_f__c,
                Last_Action__c,
                CB1_State__c,
                CB2_State__c,
                CB3_State__c,
                CB1_Session__c,
                CB2_Session__c,
                CB3_Session__c,
                CB1_Type__c,
                CB2_Type__c,
                CB3_Type__c,
                CB1_Number__c,
                CB2_Number__c,
                CB3_Number__c,
                CB1_f__c,
                CB2_f__c,
                CB3_f__c,
                Processed__c,
                Link__c,
                FIL__c,
                HCA__c,
                HCS__c,
                HFN__c,
                HBA__c,
                HPA__c,
                HFA__c,
                ENG__c,
                SCA__c,
                SCS__c,
                SFN__c,
                SBA__c,
                SPA__c,
                SFA__c,
                CCR__c,
                FBA__c,
                FFN__c,
                ENR__c,
                VET__c
                FROM
                    LTA_BillImport__c
                WHERE
                    Processed__c=null
                ORDER BY CreatedDate ASC
        ]);
    }

    public void execute(Database.BatchableContext BC, List<LTA_BillImport__c> scope) {
        Set<String> teliconIds = new Set<String>();
        for(LTA_BillImport__c bi : scope){
            teliconIds.add(bi.Bill__c);
        }
        
        Map<String, LTA_Bill__c> extIdToBillMap = new Map<String, LTA_Bill__c>();
        for(LTA_Bill__c bill : [
            SELECT  Id,
            Bill_Version__c,
            Telicon_Bill_ID__c,
            Subject__c,
            Impact__c,
            Corollary_Division_s__c,
            Legislative_Liaison_SLA__c, 
            Primary_Division__c
            FROM    LTA_Bill__c
            WHERE   Telicon_Bill_ID__c in :teliconIds]){
                extIdToBillMap.put(bill.Telicon_Bill_ID__c, bill);
            }
        
        system.debug('extIdToBillMap: ' + extIdToBillMap);
        
        List<Schema.PicklistEntry> plList = LTA_Bill__c.Bill_Version__c.getDescribe().getPicklistValues();
        system.debug('plList: ' + plList);
        
        Map<string, LTA_Bill__c> billsToInsert = new Map<string, LTA_Bill__c>();
        for(LTA_BillImport__c bi : scope){
            bi.Processed__c = batchTimeStamp; //Tag this as processed

            LTA_Bill__c newBill = new LTA_Bill__c();
            
            newBill.Name = bi.Bill_Type__c + bi.Bill_Number__c.leftPad(5, '0');
            newBill.Bill_Number__c = bi.Bill_Number__c;
            newBill.Bill_Session__c = bi.Bill_Session__c;
            newBill.Bill_Type__c = bi.Bill_Type__c;
            newBill.Bill_Author__c = bi.Bill_Author__c;
            newBill.Bill_Caption__c = bi.Bill_Caption__c;
            newBill.CB1Name__c = bi.CB1_f__c;
            newBill.CB2Name__c = bi.CB2_f__c;
            newBill.CB3Name__c = bi.CB3_f__c;
            newBill.Last_Action__c = bi.Last_Action__c;
            newBill.Link__c = bi.Link__c;
            newBill.Telicon_Bill_ID__c = bi.Bill__c;
            newBill.Bill_Version__c = null;
            newBill.Due_Date__c = batchToday.addDays(tierA_dueDays);
            
            //Identify the version based on field populated
            for (integer i = plList.size()-1; i >= 0; i--){
                string api = plList[i].getValue();
                //system.debug('picklist value list item: ' + api);
                
                string fieldName = api + '__c';
                
                try {
                    string v = (string) bi.get(fieldName);
                    if (!string.isBlank(v)) {
                        newBill.Bill_Version__c = api;
                        break;
                    }
                }
                catch(Exception ex){
                    system.debug('Error getting field [' + fieldName + ']: ' + ex.getMessage());
                }
            }
            
            if (extIdToBillMap.containsKey(bi.Bill__c)) {
                LTA_Bill__c oldBill = extIdToBillMap.get(bi.Bill__c);
                if (newBill.Bill_Version__c == oldBill.Bill_Version__c){
                    continue; //Skip this bill, nothing to do!
                }
                
                newBill.Parent__c = oldBill.Id;

                //Per requirement, carry these over from the original bill
                newBill.Legislative_Liaison_SLA__c = oldBill.Legislative_Liaison_SLA__c;
                newBill.Primary_Division__c = oldBill.Primary_Division__c;
                newBill.Corollary_Division_s__c = oldBill.Corollary_Division_s__c;
                newBill.Impact__c = oldBill.Impact__c;
                newBill.Subject__c = oldBill.Subject__c;
            }

            //Since we process older records first, this will overwrite any existing w/ latest here to prevent insert/update issues
            billsToInsert.put(newBill.Telicon_Bill_ID__c, newBill);
        }

        system.debug('billsToInsert: ' + billsToInsert);
        system.debug('billsToInsert.size(): ' + billsToInsert.size());

        List<LTA_Bill__c> billsToUpdate = new List<LTA_Bill__c>();
        for(LTA_Bill__c bill : billsToInsert.values()){
            if(extIdToBillMap.get(bill.Telicon_Bill_ID__c) != null){
                //Removing ExternalId from existing records
                billsToUpdate.add(new LTA_Bill__c(Id = extIdToBillMap.get(bill.Telicon_Bill_ID__c).Id,  Telicon_Bill_ID__c = null));
            }
        }

        SavePoint sp = database.setSavepoint();
        try{
            system.debug('billsToUpdate: ' + billsToUpdate);
            system.debug('billsToUpdate.size(): ' + billsToUpdate.size());
            update billsToUpdate;
    
            system.debug('billsToInsert: ' + billsToInsert);
            insert billsToInsert.values();
    
            system.debug('scope: ' + scope);
            update scope;
        }
        catch(Exception ex){
            system.debug(ex.getMessage());
            database.rollback(sp);
            throw ex;
        }
    }

    public void finish(Database.BatchableContext BC) { }
}